travis:
  secure:
    BINSTAR_TOKEN: bhr4QFplSNiyiaZmRHHSuAzBtM+y8IjCBQbojFUsq9Ybx1DJ/tSCdLHo8Y7NVr4rJDzN/LpmFMIS6jDcBv9SwD58RQh6Y/nw38f3jCv3pQRkfI1AMp5U7EnnfkGgUmBDh36rra7QiQrSDGgMK9ZRsq8/wuq8017WNVFB7JXvnNAF0lVykX5HvQs4V6QKNwgQu2VS5FwRZhHuz07uc0dtM9IzLFkh95YBfW97A1oq6USgBnWxvOUp5xyCE2xMG3vbeTTIu9sLQZgXmlKeEAINrEiIu0M02myxdAi+SjiznFErUsoCzUY8E4QGHJsmtgb+YtPc1lh/5GK8UWolAKgJmaL7N4QlKUMyz6pogSOjDKf5hGFhIjyuVxjV6KVlMTacf+UKFqH8Dexqx7yT7uv6u+D+QKN/Rgd/Kb9cUPbN1E8nM1n+q/gHrw8nHF3CTesuHEPWzjuO1/xLOTqwpbSxQEPZy0na3GippYoXPf2VSyiWtiy0Gq8Wmbn8AjxKqybVC2V9RI6jJ6HaYGMfP3uz6NJXTHxm7xpS9yqNH8eONWbamevbkXjVMDCVs7SF6Dx5U+ItQ3Tu4nWbollsguQIXmo4UYM+7zuJfImYo8yhinWeBGdRoQ6wlh/XIOew2xrfloJc7qd4ctTRdZawg2VfuNVU3xeqHw77/80Q3SMNPP8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
